name: pagerduty-alert
description: Simple PagerDuty integration for GitHub Actions
author: theoremlp
inputs:
  pd-integration-key:
    required: true
    description: The corresponding integration key for a PagerDuty service.
  title:
    required: true
    description: A short, human-readable title for the alert (1024 character max).
  summary:
    required: true
    description: |
      A longer text description of the event, which can include instructions to further investigate
      or resolve the incident.
  severity:
    required: true
    description: |
      The perceived severity of the status the event is describing with respect to the affected system.
      This can be critical, error, warning or info.
runs:
  using: "node16"
  main: "dist/index.js"
