name: pagerduty-alert
description: Simple PagerDuty integration for GitHub Actions
author: theoremlp
inputs:
  pd-integration-key:
    required: true
    description: The corresponding integration key for a PagerDuty service.
  summary:
    required: true
    description: |
      A brief text summary of the event, used to generate the summaries/titles of any associated alerts. 
      The maximum permitted length of this property is 1024 characters.
  description:
    required: true
    description: |
      A longer text description of the event, which can include instructions to further investigate
      or resolve the incident.
  severity:
    required: true
    description: |
      The perceived severity of the status the event is describing with respect to the affected system.
      This can be critical, error, warning or info.
runs:
  using: "node16"
  main: "dist/index.js"
